version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_backend
    user: "root"
    ports:
      - "8000:80"
    volumes:
      - ./backend:/app/backend
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: news_agregator
      DB_USERNAME: root
      DB_PASSWORD: kingsharp
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    user: "root"
    container_name: react_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    user: "root"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'kingsharp'
      MYSQL_DATABASE: 'news_agregator'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:


